feat: Updated .github/workflows/maven-ci-and-prb.y

diff --git a/.github/workflows/maven-ci-and-prb.yml b/.github/workflows/maven-ci-and-prb.yml
--- a/.github/workflows/maven-ci-and-prb.yml
+++ b/.github/workflows/maven-ci-and-prb.yml
@@ -20,7 +20,7 @@ name: Maven Build
 
 on:
   push:
-    branches: [s3mock-v2, main]
+    branches: [main]
   pull_request:
     branches: [s3mock-v2, main]
 
@@ -45,6 +45,16 @@ jobs:
         with:
           java-version: 21
           distribution: 'temurin'
-          cache: 'maven'
+          cache: true
       - name: Build with Maven
-        run: ./mvnw -B -V -Dstyle.color=always clean verify
+        run: |
+          run: |
+          ./mvnw -B -V -Dstyle.color=always clean verify
+          if [ $? -ne 0 ]; then
+            echo 'Maven build failed' >&2
+            exit 1
+          fi
+          if [ $? -ne 0 ]; then
+            echo 'Maven build failed' >&2
+            exit 1
+          fi
